"""Add start_date field in habits table

Revision ID: 2d1c59ccaff2
Revises: 37c36672d2bb
Create Date: 2024-08-29 17:24:46.298697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1c59ccaff2'
down_revision = '37c36672d2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
