"""Updated User table with auth provider info

Revision ID: 9678ebf38db0
Revises: 
Create Date: 2024-08-26 20:53:48.227150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9678ebf38db0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=postgresql.ENUM('Daily', 'Weekly', 'Monthly', 'Yearly', name='frequency_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('Daily', 'Weekly', 'Monthly', 'Yearly', name='frequency_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###
